---
name: next

on:
  push:
    branch:
      - master

jobs:
  build_staging:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type:
          - debian
    name: debian staging build container
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v4.1.1
        with:
          file: staging/Dockerfile.${{ matrix.type }}.staging
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/igaw/linux-nvme/${{ matrix.type }}.staging:next

  build_tools:
    runs-on: ubuntu-latest
    name: build muon and samurai
    needs: build_staging
    container:
      image: ghcr.io/igaw/linux-nvme/debian.staging:next
    steps:
     - uses: actions/checkout@v3
     - name: build
       run: |
         scripts/build-muon.sh
     - uses: actions/upload-artifact@v3
       name: upload artifacts to github
       with:
         name: Upload artifacts
         path: bin

  deploy_debian_containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type:
          - debian
          - debian.python
    needs: build_tools
    name: debian build containers
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v4.1.1
        with:
          file: Dockerfile.${{ matrix.type }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/igaw/linux-nvme/${{ matrix.type }}:next

  deploy_cross_containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - armhf
          - ppc64le
          - s390x
    name: ubuntu cross container
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v4.1.1
        with:
          file: Dockerfile.ubuntu.${{ matrix.arch }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/igaw/linux-nvme/ubuntu-cross-${{ matrix.arch }}:next
