---
name: Delete old container images

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  clean-ghcr:
    name: cleanup images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: linux-nvme/debian* linux-nvme/ubuntu*
          cut-off: One week ago UTC
          keep-at-least: 1
          skip-tags: latest
          account-type: personal
          token: ${{ secrets.PAT }}
