name: release

on:
  push:
    tags:
      - '*.*'

jobs:
  deploy_containers:
    name: Build and deploy container images
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Get release
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/armhf,linux/ppc64el,linux/s390x
          push: true
          tags: |
            ghcr.io/igaw/linux-nvme-build-img
            ghcr.io/igaw/linux-nvme-build-img:${{ env.RELEASE_VERSION }}
            ghcr.io/igaw/linux-nvme-build-img:latest-release
            ${{ steps.meta.outputs.tags }}
