---
name: release

on:
  push:
    tags:
      - '*.*'

jobs:
  deploy_debian_containers:
    name: debian container
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Get release
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.debian
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/igaw/linux-nvme-build-img/debian:${{ env.RELEASE_VERSION }}
            ghcr.io/igaw/linux-nvme-build-img/debian:latest-release

  deploy_cross_containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - armhf
          - ppc64le
          - s390x
    name: ubuntu cross container
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Get release
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.ubuntu.${{ matrix.arch }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/igaw/linux-nvme-build-img/ubuntu-cross-${{ matrix.arch }}:${{ env.RELEASE_VERSION }}
            ghcr.io/igaw/linux-nvme-build-img/ubuntu-cross-${{ matrix.arch }}:latest-release
